version: '2.1'
services:
  pigpiod:
    image: ae/pigpio/pigpiod:latest
    build:
      context: .
      args:
        - DEFAULT_LISTEN_PORT=8364
        - DEFAULT_BUFFER_SIZE_MS=200
        - DEFAULT_SAMPLE_INTERVAL_uS=2
    cap_add:
      - ALL
    devices:
      - /dev/mem
      - /dev/vcio
