version: '2.1'
services:
  pigpio:
    image: ae/pigpio:latest
    build:
      context: .
      args:
        - DEFAULT_LISTEN_PORT=8364
        - DEFAULT_BUFFER_SIZE_MS=200
        - DEFAULT_SAMPLE_INTERVAL_uS=2

