version: '2'
services:
  pigpiod:
    image: ae/pigpio:latest
    build:
      context: .
      args:
        - DEFAULT_LISTEN_PORT=8364
        - DEFAULT_BUFFER_SIZE_MS=200
        - DEFAULT_SAMPLE_INTERVAL_uS=2
    cap_add:
      - ALL
    devices:
      - /dev/mem
      - /dev/vcio
    command: pigpiod -s 2 -b 200 -p 8364
    expose:
      - 8364
